GET http://localhost:5000/users


###
DELETE http://localhost:5000/users/63821ae375f13915ac91a032

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username": "hello",
    "email": "user6@mail.com",
    "password": "hello :)"
}


###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "user3@mail.com",
    "password": "hello :)"
}